name = "LuxorLabels"
uuid = "bc38f42f-d837-40aa-8305-15f3941c28e9"
authors = ["hustf <hustf@users.noreply.github.com> and contributors"]
version = "0.0.1"

[deps]
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
Pango_jll = "36c8627f-9965-5494-a995-c6b170f724f3"

[compat]
julia = "1.7"
Pango_jll = "=1.42.4"